INPUT:
  HEIGHT: 600
  WIDTH: 400
DATALOADER:
  DEBUG: False
  FP_DATASET:
    ROOTDIR: ./data/fashion-dataset
    TOPK: -1
    BOTTOMK: 123
    VAL_DATA_FRACTION: 0.1
MODEL:
  ARCHITECTURE: FinetuneNet
  CONV_BODY:
    ARCH: res50
    FREEZE_NUM_BLOCKS: 2
INPUT:
    HEIGHT: 600
    WIDTH: 400
TRAIN:
  NUM_CLASSES: 123
  SHUFFLE: True
  MAX_EPOCH: 50
  LR_DECAY_EPOCH: 4
  LR_BASE: 0.01
  BATCH_SIZE: 64
  SAVE_CKPT_EPOCH: 5
  PRINT_PERIOD: 25
  PATIENCE: 4
  VAL_EPOCH: 2
  VAL_BATCH_SIZE: 64

