INPUT:
  HEIGHT: 600
  WIDTH: 400
DATALOADER:
  FP_DATASET:
    ROOTDIR: ./data/fashion-dataset
MODEL:
  ARCHITECTURE: ProtoNet
  CONV_BODY:
    ARCH: res50
  PROTONET:
    VIS_EMBEDDING_DIM: 512
    DISTANCE_METRIC: Euclidean
    #DISTANCE_METRIC: Cosine
    #COSINE_RADIUS: 8.
TRAIN:
  SHUFFLE: True
  MAX_EPISODE: 5000
  BATCH_SIZE: 1
  SAVE_CKPT_EPISODE: 500
  LR_BASE: 0.001
  LR_DECAY: 0.5
  LR_DECAY_EPISODE: 1000
  PRINT_PERIOD: 100
OUTPUT_DIR: './checkpoints/res50_fewshot'
